const Images = {
  splashScreen: require('./img/spalshscreen.png'),
  home: require('./img/home.png'),
  homeC: require('./img/homeC.png'),
  ultiti: require('./img/ultiti.png'),
  ultitiC: require('./img/ultitiC.png'),
  earncoin: require('./img/earncoin.png'),
  earncoinC: require('./img/earncoinC.png'),
  notification: require('./img/notification.png'),
  notificationC: require('./img/notificationC.png'),
  personal: require('./img/personal.png'),
  personalC: require('./img/personalC.png'),
  imgHeader: require('./img/imgHeader.png'),
  knoob: require('./img/knoob.png'),
  borderWheel: require('./img/borderwheel.png'),
  money: require('./img/money.png'),
  card: require('./img/card.png'),
  camera: require('./img/camera.png'),
  history: require('./img/history.png'),
  back: require('./img/back.png'),
  imgProfile: require('./img/imgProfile.png'),
  imgNotifi: require('./img/imgNotifi.png'),
  logoNews: require('./img/logoNews.png'),
  imageTest: require('./img/imageTest.png'),
};
export default Images;
